myapp/api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.HomeAPIView.as_view(), name="home"),
    path('users/signup/', views.CreateView.as_view(), name="signup"),
    path('users/login/', views.LoginAPIView.as_view(), name="login"),
    path('users/profile/', views.ProfileAPIView.as_view(), name="profile"),
    path('users/changepassword/', views.UserChangePassword.as_view(), name='user_change_password'),
    path('users/password_reset_sent/', views.SendResetLinkView.as_view(), name='password_reset_sent'),
    path('users/reset/<uid>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('posts/', views.PostAPIView.as_view(), name="add_post"),
    path('posts/<int:pk>/', views.UpdateDeletePost.as_view(), name='Update_Delete_post'),
    path('comments/', views.CommentAPIView.as_view(), name="add_comment"),
    path('comments/<int:comm_pk>/', views.CommentUpdateDeleteAPIView.as_view(), name="Update_Delete_comment"),
    path('likes/', views.LikeAPIView.as_view(), name="likes"),
    path('search/', views.SearchUserAPIView.as_view(), name='search'),
    path('search/users/', views.SearchAllUserAPIView.as_view(), name='search_all'),
    path('users/profile/<int:pk>/', views.ProfileRetrieveAPIView.as_view(), name='profile_retrieve'),
]

myapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView

from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
    PasswordResetDoneView

urlpatterns = [
                  path('signup/', views.SignupView.as_view(), name='signup'),
                  path('login/', views.LoginView.as_view(), name='login'),
                  path('', views.HomeView.as_view(), name='home'),
                  path('logout/', views.LogoutView.as_view(), name='logout'),
                  path('profile/', views.ProfileView.as_view(), name='profile'),
                  path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
                  path("delete-profile/<int:pk>/", views.DeleteProfileView.as_view(), name="delete_profile"),
                  path('changepassword/', views.ChangePasswordView.as_view(), name='changepassword'),
                  path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
                  path("password_reset_sent/", TemplateView.as_view(template_name='myapp/passwordresetdone.html')),
                  path("reset/<uidb64>/<token>/", views.ResetPasswordConfirmView.as_view(),
                       name="password_reset_confirm"),
                  path("add-post/", views.AddPostView.as_view(), name="add_post"),
                  path("edit-post/<int:pk>/", views.EditPostView.as_view(), name="edit_post"),
                  path("delete-post/<int:pk>/", views.DeletePostView.as_view(), name="delete_post"),
                  path("likepost/", views.LikeView.as_view(), name="like_post"),
                  path("createcomment/", views.CommentCreateView.as_view(), name="createcomment"),
                  path("commentdelete/", views.CommentDeleteView.as_view(), name="commentdelete"),
                  path("commentupdate/", views.CommentUpdateView.as_view(), name="commentupdate"),

                  path('search/', views.SearchUser.as_view(), name='search'),
                  path('search/users/', views.SearchAllUser.as_view(), name='search_all'),
                  path('profile/<int:pk>/', views.ProfileRetrieve.as_view(), name='profile_retrieve'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('api/', include('myapp.api.urls'))
]

myapp/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager


# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = None
    email = models.EmailField(_('email_address'), unique=True, max_length=200)
    date_joined = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    first_name = models.CharField(max_length=75,blank=False)
    last_name = models.CharField(max_length=75,blank=False)
    image = models.ImageField(upload_to='profile')
    bio = models.TextField(null=True)
    phone = models.CharField(max_length=10)
    dob = models.DateField()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class PostModel(models.Model):
    caption = models.TextField(blank=True)
    post_image = models.ImageField(upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        db_table = "post"


class LikesModel(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE)

    class Meta:
        db_table = 'likes'


class CommentModel(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='comment')
    comment = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'comment'

myapp/api/views.py
from django.contrib.auth import authenticate
from django.db.models import Count, Q, Prefetch
from rest_framework.response import Response
from rest_framework.views import APIView
from .custompermission import MyPermission
from .serializers import CustomUserSerializer, PostSerializer, CommentSerializer, \
    ChangePasswordSerializer, SendResetLinkSerializer, PasswordResetConfirmSerializer, ProfileSerializer
from rest_framework.generics import CreateAPIView
from myapp.models import CustomUser, PostModel, LikesModel, CommentModel
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.tokens import RefreshToken


# Create your views here.
class CreateView(CreateAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer


def get_tokens_for_user(user):
    refresh = RefreshToken.for_user(user)

    return {
        'refresh': str(refresh),
        'access': str(refresh.access_token),
    }


def validateEmail(email):
    from django.core.validators import validate_email
    from django.core.exceptions import ValidationError
    try:
        validate_email(email)
        return True
    except ValidationError:
        return False


class LoginAPIView(APIView):
    def post(self, request):
        email = request.data.get('email')
        password = request.data.get('password')
        response = {}
        if email and password:
            if validateEmail(email):
                user = authenticate(request, email=email, password=password)
                if user:
                    return Response({'data': get_tokens_for_user(user)}, status=status.HTTP_200_OK)
                return Response({'errors': 'Credential is not valid'}, status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response({'errors': {'Email': 'This Field not Valid'}}, status=status.HTTP_400_BAD_REQUEST)
        if not email:
            response["email"] = ["This field is required"]
        if not password:
            response["password"] = ["This field is required"]
        return Response({"errors": response})


class ProfileAPIView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = CustomUser.objects.get(id=request.user.id)
        user_serializer = ProfileSerializer(user)
        posts = PostModel.objects.filter(user_id=request.user.id).order_by('-id').annotate(
            like=Count('likesmodel')).values()
        for post in posts:
            post['comments'] = CommentModel.objects.filter(post_id=post['id']).values()
        context = {
            'user': user_serializer.data,
            'posts': posts
        }
        return Response({'data': context}, status=status.HTTP_200_OK)

    def put(self, request):
        user = CustomUser.objects.get(id=request.user.id)
        user_serializer = CustomUserSerializer(user, data=request.data, partial=True)
        if user_serializer.is_valid():
            user_serializer.save()
            return Response({'message': 'Updated Successfully'}, status=status.HTTP_200_OK)
        return Response({'errors': user_serializer.errors}, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request):
        user = CustomUser.objects.get(id=request.user.id)
        user.delete()
        return Response({'message': 'Delete Successfully'}, status=status.HTTP_200_OK)


class UserChangePassword(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        change_password_serializer = ChangePasswordSerializer(data=request.data, context={'user': request.user})
        if change_password_serializer.is_valid(raise_exception=True):
            return Response({'msg': 'Change Password Successfully.'}, status=status.HTTP_200_OK)
        return Response({'errors': change_password_serializer.errors}, status=status.HTTP_400_BAD_REQUEST)


class SendResetLinkView(APIView):
    def post(self, request):
        restlinkserailizer = SendResetLinkSerializer(data=request.data)
        if restlinkserailizer.is_valid():
            return Response({'msg': 'Reset Link is Sent To Your Email.'}, status=status.HTTP_200_OK)
        return Response({'errors': restlinkserailizer.errors}, status=status.HTTP_400_BAD_REQUEST)


class PasswordResetConfirmView(APIView):
    def post(self, request, uid, token):
        resetserializer = PasswordResetConfirmSerializer(data=request.data, context={'uid': uid, 'token': token})
        if resetserializer.is_valid():
            return Response({'msg': 'Password Reset Successfully'}, status=status.HTTP_200_OK)
        return Response({'errors': resetserializer.errors}, status=status.HTTP_400_BAD_REQUEST)


class PostAPIView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        request.data['user'] = request.user.pk
        post_serializer = PostSerializer(data=request.data)
        if post_serializer.is_valid():
            post_serializer.save()
            return Response({'data': post_serializer.data}, status=status.HTTP_201_CREATED)
        return Response({'data': post_serializer.errors}, status=status.HTTP_400_BAD_REQUEST)


class UpdateDeletePost(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [MyPermission]

    def delete(self, request, pk):
        post = PostModel.objects.filter(pk=pk).first()
        if post:
            self.check_object_permissions(request, post)
            post.delete()
            return Response({'msg': 'Deleted Successfully'}, status=status.HTTP_200_OK)
        return Response({"msg": "No Post Found"}, status=status.HTTP_404_NOT_FOUND)

    def put(self, request, pk):
        post = PostModel.objects.filter(pk=pk).first()
        if post:
            self.check_object_permissions(request, post)
            post_serializer = PostSerializer(post, data=request.data, partial=True)
            if post_serializer.is_valid():
                post_serializer.save()
                return Response({'msg': 'updated Successfully'}, status=status.HTTP_200_OK)
            return Response({'errors': post_serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
        return Response({"msg": "No Post Found"}, status=status.HTTP_404_NOT_FOUND)


class CommentAPIView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        post_id = request.data.get('post_id')
        comment = request.data.get('comment_val')
        response = {}
        if post_id and comment:
            post_obj = PostModel.objects.filter(id=post_id).first()
            if post_obj:
                new_comment = CommentModel.objects.create(post=post_obj, user_id=request.user.id, comment=comment)
                context = {
                    "comment_id": new_comment.id,
                    "comment_content": new_comment.comment,
                    "comment_created_at": new_comment.created_at
                }
                return Response({"data": context})
            response["post_id"] = ["Post Is Not Found"]
            return Response({'errors': response})
        if not post_id:
            response["post_id"] = ["This field is required"]
        if not comment:
            response["comment"] = ["This field is required"]
        return Response({"errors": response})


class CommentUpdateDeleteAPIView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [MyPermission]

    def put(self, request, comm_pk):
        comment = CommentModel.objects.filter(id=comm_pk).first()
        if comment:
            self.check_object_permissions(request, comment)
            comm_serializer = CommentSerializer(comment, data=request.data, partial=True)
            if comm_serializer.is_valid():
                comm_serializer.save()
                return Response({'msg': 'updated Successfully'}, status=status.HTTP_200_OK)
            return Response({'errors': comm_serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
        return Response({'errors': 'No Comment Found'}, status=status.HTTP_404_NOT_FOUND)

    def delete(self, request, comm_pk):
        comment = CommentModel.objects.filter(id=comm_pk).first()
        if comment:
            self.check_object_permissions(request, comment)
            comment.delete()
            return Response({'msg': 'deleted successfully'}, status=status.HTTP_200_OK)
        return Response({'errors': 'No Comment Found'}, status=status.HTTP_404_NOT_FOUND)


class LikeAPIView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        post_id = request.data.get('post_id')
        if post_id:
            post = PostModel.objects.filter(id=post_id).first()
            if post:
                like = LikesModel.objects.filter(post__id=post_id, user=request.user).first()
                if like:
                    like.delete()
                    return Response({'msg': 'dislike successfully'}, status=status.HTTP_200_OK)
                like = LikesModel(post=post, user=request.user)
                like.save()
                return Response({'msg': 'liked Successfully'}, status=status.HTTP_200_OK)
            return Response({'errors': 'Post is Not Found'}, status=status.HTTP_404_NOT_FOUND)
        error = {}
        if post_id is None:
            error["post_id"] = "This is Field Required"
        else:
            error["post_id"] = "This is Field Can't Be Empty"
        return Response({'errors': error})


class HomeAPIView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):

templates/myapp/edit.html
{% extends 'myapp/base.html' %}
{% block title %}Edit{% endblock title %}
{% block style %}
<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
</style>
{% endblock style %}
{% block content %}
{% load widget_tweaks %}
    <div class="bg-blue-100" style="background-color:#E5E5E5;!important">
        <div class="flex justify-center items-center mx-auto">
            <div class="w-1/2 p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 ">
                {% include 'myapp/messages.html' %}
        <h1 class="text-2xl font-bold my-3">Edit</h1>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% comment %} {{form.as_p}} {% endcomment %}
                    <div class="grid md:grid-cols-2 md:gap-6">
                        <div class="relative z-0 w-full mb-5 group">
                            {{form.first_name|add_class:'block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer'|attr:'placeholder: '}}
                            <label for="floating_first_name" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">First name</label>
                            <span class="text-red-400">{{form.first_name.errors|striptags}}</span>
                        </div>
                        <div class="relative z-0 w-full mb-5 group">
                            {{form.last_name|add_class:'block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer'|attr:'placeholder: '}}
                            <label for="floating_last_name" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Last name</label>
                            <span class="text-red-400">{{form.last_name.errors|striptags}}</span>
                        </div>
                    </div>
                    <div class="relative z-0 w-full mb-3 group">
                        {{form.email|add_class:"block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"|attr:'placeholder: '}}
                        <label for="floating_email" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email address</label>
                        <span class="text-red-400">{{form.email.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-3 group">
                        <label class="block mb-2 text-base font-medium text-gray-900">Upload Image</label>
                        {{form.image|add_class:"block w-full mb-2 text-xs text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none"}}
                        <span class="text-red-400">{{form.image.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-5 group">
                        <label for="message" class="block mb-2 text-base font-medium text-gray-900">Your Bio</label>
                        {{form.bio|add_class:'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500'|attr:'rows:3'|attr:'style:resize: none;'}}
                        <span class="text-red-400">{{form.bio.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-3 group">
                        {{form.phone|add_class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"|attr:'placeholder: '}}
                        <label for="floating_phone" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Phone number</label>
                        <span class="text-red-400">{{form.phone.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-4 group">
                        <label class="block text-base font-medium text-gray-900">Date of Birth</label>
                        {{form.dob|add_class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"}}
                        <span class="text-red-400">{{form.dob.errors|striptags}}</span>
                    </div>

                <div class="flex">
            <div class="mt-2 text-gray-900 text-base font-medium">Password: </div>
            <div class="mt-2 mx-2 text-blue-500"><a href="{% url 'changepassword' %}">Change My Password</a></div>
        </div>
                    {{form.non_field_errors}}
                    <div class="w-full items-center">
                        <button type="submit" class="rounded bg-blue-700 py-2 my-3 text-white w-1/5">Edit</button>
                        <a href="{% url 'profile' %}" class="py-3 my-3 mx-2 text-blue-500 underline w-1/5">Cancel</a>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    $("#id_phone").keypress(function(){
        if($("#id_phone").val().length == 10){
            return false;
        }
    });
</script>
{% endblock script %}

templates/myapp/signup.html
{% extends 'myapp/base.html' %}

{% block title %}SIGNUP{% endblock title %}
{% block style %}
<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
</style>
{% endblock style %}
{% block navbar %}{% endblock navbar %}
{% block content %}
{% load widget_tweaks %}
    <div class="bg-blue-100" style="background-color:#E5E5E5;!important">
        <div class="flex justify-center items-center mx-auto md:h-screen">
            <div class="w-1/2 p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
                {% include 'myapp/messages.html' %}
        <h1 class="text-2xl font-bold my-3">REGISTRATION</h1>
                <form action="" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    {% comment %} {{form.as_p}} {% endcomment %}
                    <div class="grid md:grid-cols-2 md:gap-6">
                        <div class="relative z-0 w-full mb-5 group">
                            {{form.first_name|add_class:'block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer'|attr:'placeholder: '}}
                            <label for="floating_first_name" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">First name</label>
                            <span class="text-red-400">{{form.first_name.errors|striptags}}</span>
                        </div>
                        <div class="relative z-0 w-full mb-5 group">
                            {{form.last_name|add_class:'block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer'|attr:'placeholder: '}}
                            <label for="floating_last_name" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Last name</label>
                            <span class="text-red-400">{{form.last_name.errors|striptags}}</span>
                        </div>
                    </div>
                    <div class="relative z-0 w-full mb-3 group">
                        {{form.email|add_class:"block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer invalid:border-red-500"|attr:'placeholder: '}}
                        <label for="floating_email" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email address</label>
                        <span class="text-red-400">{{form.email.errors|striptags}}</span>
                        <span class="invisible peer-invalid:visible peer-invalid:visible bg-red-200 text-red">Invalid Email</span>
                    </div>
                    <div class="relative z-0 w-full mb-3 group">
                        <label class="block mb-2 text-base font-medium text-gray-900">Upload Image</label>
                        {{form.image|add_class:"block w-full mb-2 text-xs text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none"}}
                        <span class="text-red-400">{{form.image.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-5 group">
                        <label for="message" class="block mb-2 text-base font-medium text-gray-900">Your Bio</label>
                        {{form.bio|add_class:'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500'|attr:'rows:3'|attr:'style:resize: none;'}}
                        <span class="text-red-400">{{form.bio.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-3 group">
                        {{form.phone|add_class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"|attr:'placeholder: '}}
                        <label for="floating_phone" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Phone number</label>
                        <span class="text-red-400">{{form.phone.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-4 group">
                        <label class="block text-base font-medium text-gray-900">Date of Birth</label>
                        {{form.dob|add_class:"block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"}}
                        <span class="text-red-400">{{form.dob.errors|striptags}}</span>
                    </div>
                    <div class="relative z-0 w-full mb-2 group">
                        {{form.password|add_class:"block py-2.5 px-0 w-full text-base text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"|attr:'placeholder: '}}
                        <label for="floating_repeat_password" class="peer-focus:font-medium absolute text-base text-gray-500 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Password</label>
                        <span class="text-red-400">{{form.password.errors|striptags}}</span>
                    </div>
                    <button type="submit" class="rounded bg-blue-700 py-2 my-3 text-white w-full">Signup</button>
                </form>
                <div class="flex">
                    <div class="mt-2 text-gray-500">Already have an account? </div>
                    <div class="mt-2 mx-2 text-blue-800"><a href="{% url 'login' %}">Login</a></div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
<script>
    $("#id_phone").keypress(function(){
        if($("#id_phone").val().length == 10){
            return false;
        }
    });
</script>
{% endblock script %}